server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-api/**

        - id: creditCardService
          uri: lb://CREDITCARD-SERVICE
          predicates:
            - Path=/creditcard-api/**

        - id: billService
          uri: lb://BILL-SERVICE
          predicates:
            - Path=/bill-api/**