server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

spring:
  application:
    name: CREDITCARD-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/gocredit
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
  config:
    import: configserver:http://localhost:8888/
  profiles:
    active: dev